### ISSUE TITLE
Non-static method BFStopTokenGenerator

### ISSUE THREAD

**Issue by allen999354** [codeling/bfstop#211] opened 2024-02-02 23:54 UTC
Got this error today from BruteForce Stop. I have no idea what it means, but I'm guessing it is a bug that needs to be reported.

-----------------------------------

Exception Type: Error
File: /home/[REDACTED]/public_html/plugins/system/bfstop/bfstop.php
Line: 56
Message: Non-static method BFStopTokenGenerator::getToken() cannot be called statically 
#0 /home/[REDACTED]/public_html/plugins/system/bfstop/bfstop.php(134): plgSystembfstop->getUnblockLink()
#1 /home/[REDACTED]/public_html/plugins/system/bfstop/bfstop.php(164): plgSystembfstop->block()
#2 /home/[REDACTED]/public_html/plugins/system/bfstop/bfstop.php(333): plgSystembfstop->blockIfTooManyAttempts()
#3 /home/[REDACTED]/public_html/libraries/src/Plugin/CMSPlugin.php(289): plgSystembfstop->onUserLoginFailure()
#4 /home/[REDACTED]/public_html/libraries/vendor/joomla/event/src/Dispatcher.php(486): Joomla\CMS\Plugin\CMSPlugin->Joomla\CMS\Plugin\{closure}()
#5 /home/[REDACTED]/public_html/libraries/src/Application/EventAware.php(111): Joomla\Event\Dispatcher->dispatch()
#6 /home/[REDACTED]/public_html/libraries/src/Application/CMSApplication.php(893): Joomla\CMS\Application\WebApplication->triggerEvent()
#7 /home/[REDACTED]/public_html/libraries/src/Application/SiteApplication.php(675): Joomla\CMS\Application\CMSApplication->login()
#8 /home/[REDACTED]/public_html/components/com_users/src/Controller/UserController.php(90): Joomla\CMS\Application\SiteApplication->login()
#9 /home/[REDACTED]/public_html/libraries/src/MVC/Controller/BaseController.php(693): Joomla\Component\Users\Site\Controller\UserController->login()
#10 /home/[REDACTED]/public_html/libraries/src/Dispatcher/ComponentDispatcher.php(143): Joomla\CMS\MVC\Controller\BaseController->execute()
#11 /home/[REDACTED]/public_html/libraries/src/Component/ComponentHelper.php(361): Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch()
#12 /home/[REDACTED]/public_html/libraries/src/Application/SiteApplication.php(208): Joomla\CMS\Component\ComponentHelper::renderComponent()
#13 /home/[REDACTED]/public_html/libraries/src/Application/SiteApplication.php(249): Joomla\CMS\Application\SiteApplication->dispatch()
#14 /home/[REDACTED]/public_html/libraries/src/Application/CMSApplication.php(293): Joomla\CMS\Application\SiteApplication->doExecute()
#15 /home/[REDACTED]/public_html/includes/app.php(61): Joomla\CMS\Application\CMSApplication->execute()
#16 /home/[REDACTED]/public_html/index.php(32): require_once('/home/[REDACTED]/...')
#17 {main}
Request information
GET variables
Array
(
)
POST variables
Array
(
    [username] => [REDACTED]
    [password] => [REDACTED]
    [Submit] => 
    [option] => com_users
    [task] => user.login
    [return] => aW5kZXgucGhwP0l0ZW1pZD0xNjg4
    [baf8a958339b9e9bca66e1111e65f6f9] => 1
)
COOKIE variables
Array
(
    [nrid] => 84da38176b2590a0
    [_fbp] => fb.1.1706627458346.44529567
    [jlms_hcLayout] => default
    [8f00c4d4c30ec42fbf53f24bba721771] => krddj3ptclkjec6ri0peh8d1ma
    [_s] => fgprk8aiikbrkct45b1pf25e96
    [_gid] => GA1.2.419887213.1706905346
    [_ga] => GA1.1.440104736.1706627455
    [idev] => 280--0-0-------https://[REDACTED]
    [_ga_KL8WDWMBFS] => GS1.1.1706912439.4.1.1706912483.16.0.0
)
REQUEST variables
Array
(
    [username] => [REDACTED]
    [password] => [REDACTED]
    [Submit] => 
    [option] => com_users
    [task] => user.login
    [return] => aW5kZXgucGhwP0l0ZW1pZD0xNjg4
    [baf8a958339b9e9bca66e1111e65f6f9] => 1
)
SERVER variables
Array
(
    [PATH] => /usr/local/bin:/bin:/usr/bin
    [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
    [HTTP_ACCEPT_ENCODING] => gzip, deflate, br
    [HTTP_ACCEPT_LANGUAGE] => en-US,en;q=0.9
    [CONTENT_TYPE] => application/x-www-form-urlencoded
    [CONTENT_LENGTH] => 179
    [HTTP_COOKIE] => nrid=84da38176b2590a0; _fbp=fb.1.1706627458346.44529567; jlms_hcLayout=default; 8f00c4d4c30ec42fbf53f24bba721771=krddj3ptclkjec6ri0peh8d1ma; _s=fgprk8aiikbrkct45b1pf25e96; _gid=GA1.2.419887213.1706905346; _ga=GA1.1.440104736.1706627455; idev=280--0-0-------https%3A%2F%2F[[REDACTED]](http://[REDACTED]/)%2Festore; _ga_KL8WDWMBFS=GS1.1.1706912439.4.1.1706912483.16.0.0
    [HTTP_HOST] => www.certifiedinfosec.com
    [HTTP_REFERER] => https://[REDACTED]/e-learning
    [HTTP_USER_AGENT] => Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0
    [HTTP_CACHE_CONTROL] => max-age=0
    [HTTP_SEC_CH_UA] => "Not A(Brand";v="99", "Microsoft Edge";v="121", "Chromium";v="121"
    [HTTP_SEC_CH_UA_MOBILE] => ?0
    [HTTP_SEC_CH_UA_PLATFORM] => "Windows"
    [HTTP_UPGRADE_INSECURE_REQUESTS] => 1
    [HTTP_ORIGIN] => https://[REDACTED]/
    [HTTP_SEC_FETCH_SITE] => same-origin
    [HTTP_SEC_FETCH_MODE] => navigate
    [HTTP_SEC_FETCH_USER] => ?1
    [HTTP_SEC_FETCH_DEST] => document
    [HTTP_X_HTTPS] => 1
    [DOCUMENT_ROOT] => /home/[REDACTED]/public_html
    [REMOTE_ADDR] => 204.48.38.236
    [REMOTE_PORT] => 19875
    [SERVER_ADDR] => 103.72.76.172
    [SERVER_NAME] => [REDACTED]
    [SERVER_ADMIN] => [[REDACTED]
    [SERVER_PORT] => 443
    [REQUEST_SCHEME] => https
    [REQUEST_URI] => /e-learning
    [REDIRECT_URL] => /e-learning
    [REDIRECT_REQUEST_METHOD] => POST
    [HTTPS] => on
    [CRAWLER_USLEEP] => 1000
    [CRAWLER_LOAD_LIMIT] => 1
    [CRAWLER_LOAD_LIMIT_ENFORCE] => 5
    [HTTP_AUTHORIZATION] => 
    [REDIRECT_STATUS] => 200
    [X_SPDY] => HTTP3
    [SSL_PROTOCOL] => QUIC
    [SSL_CIPHER] => TLS_AES_128_GCM_SHA256
    [SSL_CIPHER_USEKEYSIZE] => 128
    [SSL_CIPHER_ALGKEYSIZE] => 128
    [SCRIPT_FILENAME] => /home/[REDACTED]/public_html/index.php
    [QUERY_STRING] => 
    [SCRIPT_URI] => https://[REDACTED]/e-learning
    [SCRIPT_URL] => /e-learning
    [SCRIPT_NAME] => /index.php
    [SERVER_PROTOCOL] => HTTP/1.1
    [SERVER_SOFTWARE] => LiteSpeed
    [REQUEST_METHOD] => POST
    [X-LSCACHE] => on,crawler
    [PHP_SELF] => /index.php
    [REQUEST_TIME_FLOAT] => 1706912798.5454
    [REQUEST_TIME] => 1706912798
)

**Comment by codeling** [comment] 2024-02-03 00:20
thanks for reporting this!

the problem is fixed in the git repositories' main branch already via this commit: https://github.com/codeling/bfstop/commit/ee7641e26a051ae65ebd01636e1595967557bc18
The upcoming version 1.5.0 will include this fix.

As a workaround, you can also temporarily disable the strict error_reporting in your php configuration (see https://www.php.net/manual/en/function.error-reporting.php).

Am 3. Februar 2024 00:54:24 MEZ schrieb allen999354 ***@***.***>:

**Closed** 2024-02-08 14:50 UTC
Labels: bug
