### ISSUE TITLE
Creation of dynamic property plgSystembfstop::$notifier is deprecated

### ISSUE THREAD

**Issue by Bramfield** [codeling/bfstop#197] opened 2023-07-11 11:01 UTC
Good day!
Why do I see Creation of dynamic property plgSystembfstop::$notifier is deprecated?
The full error in Joomla 4 admin looks like this: WARNING No proper remote IP address available, falling back to REMOTE_ADDR ""!
/PHP 8.2.6 version/
tnx

**Comment by Bramfield** [comment] 2023-07-14 07:37
I want to clarify that this notification is shown on all pages of the site.

maybe there is some solution?

**Comment by codeling** [comment] 2023-07-14 14:14
Thanks for reporting!

The first part of the message you see () is a deprecation warning, so only a cosmetic issue at the moment.

I will integrate a fix in a future version of bfstop, though I don't know yet when I'll release a new version yet (I probably won't release one just for this fix).

If you absolutely need to get rid of the warning, find the bfstop.php, and add a line `private $notifier;` under `private $logger;` (see https://github.com/codeling/bfstop/blob/37abf2bf2540f55a4f90456a73bfe9b302b3471e/bfstop.php#L23). The file can be found under plugins/system/bfstop.


The second part about no proper IP address is a server configuration issue - your server is probably behind a load balancer or proxy and therefore potentially has problems determining the actual client IP address.

**Comment by Bramfield** [comment] 2023-07-14 14:55
> Thanks for reporting!
> 
> The first part of the message you see (Creation of dynamic property plgSystembfstop::$notifier is deprecated) is a deprecation warning, so only a cosmetic issue at the moment.
> 
> I will integrate a fix in a future version of bfstop, though I don't know yet when I'll release a new version yet (I probably won't release one just for this fix).
> 
> If you absolutely need to get rid of the warning, find the bfstop.php, and add a line `private $notifier;` under `private $logger;` (see
> 
> https://github.com/codeling/bfstop/blob/37abf2bf2540f55a4f90456a73bfe9b302b3471e/bfstop.php#L23
> ). The file can be found under plugins/system/bfstop in your joomla installation.
> 
> The second part about no proper IP address is a server configuration issue - your server is probably behind a load balancer or proxy and therefore potentially has problems determining the actual client IP address. There's nothing more that bfstop can do about this as far as I can tell.

thank you for support

**Comment by codeling** [comment] 2023-07-16 11:42
The deprecation warning is fixed in main branch:  https://github.com/codeling/bfstop/commit/1dbdf6bf40527f495dd36bf52858e7494f695318

**Comment by Bramfield** [comment] 2023-08-29 08:14
Hello
Now another notification is displayed:
Deprecated
: Creation of dynamic property plgSystembfstop::$logger is deprecated in /plugins/system/bfstop/bfstop.php on line 191

**Comment by codeling** [comment] 2023-09-09 19:32
I cannot reproduce this. With the fix as linked to above (https://github.com/codeling/bfstop/commit/1dbdf6bf40527f495dd36bf52858e7494f695318) applied, there is no more output. I suspect that instead of *adding* a line with `private $notifier`, you replaced the `private $logger` line?

Make sure your bfstop.php looks [like this](https://raw.githubusercontent.com/codeling/bfstop/main/bfstop.php).

**Closed by codeling** 2023-09-09 19:32 UTC
Labels: bug

**Comment by codeling** [comment] 2023-09-09 19:35
As a side remark, at least on production servers I highly recommend to set php's `error_reporting` to `E_ALL & ~E_DEPRECATED & ~E_STRICT`, and also set `display_errors` to `Off`, both of which are workarounds for the problem of seeing the warning on every page.
