### ISSUE TITLE
1.3 clean installation cannot send emails

### ISSUE THREAD

**Issue by emeyer444** [codeling/bfstop#100] opened 2015-03-07 13:46 UTC
I was very happy on Joomla 2.5, but when I upgraded to 3.3 I started getting alot of strange behavior. I deleted all the files and database tables manually, and installed fresh. When I try sending a test email I get a php error 'cannot find class xxxx in administrator...../settings.php.I look in the plugin, that is what it is calling. I look in the settings.php file, and just as the error message says, the class is not there....I was very disappointed. What should I do?

**Comment by codeling** [comment] 2015-03-07 14:50
The settings.php file is included in the release as well as in the manifest file, and should be in the controllers folder. So your situation sounds to me like the installation somehow was incomplete.
How did you do the ugprade from 2.5 to 3.3? Have you tried reinstalling the bfstop package?

**Comment by emeyer444** [comment] 2015-03-10 00:15
Thank you for replying. I had this problem with some other updates, so I did some investigation, and I think I figured out the problem. After deleting files in the administrator/cache directory manually and reinstalling, it works, The 'clear cache' command in Joomla 3.3 does not clear the administrator cache.

**Comment by emeyer444** [comment] 2015-03-10 00:57
Also, I just discovered, the debug plugin has to be enabled (I had it disabled on my production server) for it to work, which is no issue really, but maybe worth noting.

**Comment by codeling** [comment] 2015-03-10 08:41
Not sure why clearing the cache would be required as bfstop doesn't use it, so I suppose the reinstallation did the trick. Glad that it helped in any case!

> Also, I just discovered, the debug plugin has to be enabled (I had it disabled on my production server) for it to work, which is no issue really, but maybe worth noting.

Thanks for this hint, I wasn't aware of that. However I just tried with disabled Debug plugin and bfstop seems still to work fine for me. Could you give details as to what doesn't work for you when the Debug plugin is disabled? Thanks!

**Comment by emeyer444** [comment] 2015-03-10 09:39
You know I am still trying to figure out exactly why there was a problem, and maybe I was making wrong assumptions. Is it possible it did not work right away because it needed to start in a new session, and the old session was still on keepalive?

I also dont know if there is any issue with interaction with other system plugins or with plugin order.

**Comment by codeling** [comment] 2015-03-10 20:58
> Is it possible it did not work right away because it needed to start in a new session, and the old session was still on keepalive?

You mean that above error occured because of an old session? Can't imagine how that could cause a file to go missing.

> I also dont know if there is any issue with interaction with other system plugins or with plugin order. 

What about the debug plugin, what behavior did you notice when you had it disabled?

**Comment by emeyer444** [comment] 2015-03-11 09:10
What I observed was that I had to wait some time before testing either the email or the block. At first I thought it was the cache, but maybe the block could not have have worked at first because  I still had an open session from before it started checking. When I left it for a while and came back it had started working.

**Comment by codeling** [comment] 2015-06-13 20:44
Do you still encounter any problems? As this doesn't seem to be reproducible anymore, I would close it in the next few days.

**Comment by codeling** [comment] 2015-09-15 21:59
@emeyer444 do I interpret the silence correctly as that this has resolved itself? Closing, please comment if the problem persists.

**Closed by codeling** 2015-09-15 21:59 UTC
Labels: non-reproducible, question
