### ISSUE TITLE
update system

### ISSUE THREAD

**Issue by oryxnl** [codeling/bfstop#158] opened 2017-06-29 10:29 UTC
Get the message: "Update: Kan updatesite # 29 "BFStop Package Update Server" niet openen, URL: https://bfstop.bfroehler.info/update.xml"

**Comment by codeling** [comment] 2017-06-29 15:29
Seems to be a duplicate of this issue: https://github.com/codeling/bfstop/issues/149
Can you check it and see if you find something similar in your setup to the one described there?
At the moment I cannot reproduce this issue.

**Comment by oryxnl** [comment] 2017-06-29 15:59
Hello Bernhard,

The error appears when I'm on page
/administrator/index.php?option=com_installer&view=update
and press the button "find updates".

The issue looks very similar to #149 indeed.
I have no clues what could be wrong; usually the update system works fine.
Perhaps some safety mechanism?

[image: Inline afbeelding 1]





2017-06-29 17:29 GMT+02:00 Bernhard Froehler <notifications@github.com>:

**Comment by codeling** [comment] 2017-07-03 15:23
Is your Joomla! also running on a Cent OS server?

**Comment by oryxnl** [comment] 2017-07-03 15:50
Hi Bernhard,

I'm on shared hosting and don't know more details of the server
configuration than listed in the screenshot.

2017-07-03 17:23 GMT+02:00 Bernhard Froehler <notifications@github.com>:

**Comment by codeling** [comment] 2017-07-31 07:41
The most likely reason (at least it's my current strong suspect in the [related issue](https://github.com/codeling/bfstop/issues/149) ) is that your hoster doesn't have an up-to-date list of trusted certificates on your server.
This leads to the ssl certificate on the update server which is signed by [letsencrypt](https://letsencrypt.org/) not being recognized as a valid certification authority (which it is since April 2016).
On a shared hosting you probably can't change this yourself (though you might want to check whatever configuration options your hoster provides, maybe you can adapt the trusted certification authorities somehow). Otherwise you'd have to contact your hoster (you might want to ask in general about his upgrade policy - not updating is generally a bad sign in terms of security).

**Closed** 2017-07-31 07:48 UTC
Labels: duplicate
