### ISSUE TITLE
Won’t start logging any activities.

### ISSUE THREAD

**Issue by extreme855** [codeling/bfstop#186] opened 2021-09-22 10:42 UTC
After installed I activated it and gave it some time. 
I have running of course an User actions Log to see if there was some activity and there is them a lot. 

Any ideas ?

**Comment by codeling** [comment] 2021-09-22 10:57
There's a simple way to test if  bfstop is working or not - simply try to enter invalid credentials in the login page and see if they turn up in the "failed logins" page.

**Comment by extreme855** [comment] 2021-09-22 11:05
Made tests from different devices no activity.

**Comment by codeling** [comment] 2021-09-22 11:32
By "activity" I guess you mean entries like "username and pasword wrong or account does not exist" in your error.php?

**Comment by extreme855** [comment] 2021-09-22 11:59
User activity log where is
Action/Extension/Date/Name/IP Address/ID tabs where is different information about what are users doing. 

I have some logs where like 
User (#username) logged in to admin
User (#username) tried to logged in to admin
 And more ....

But bfstop doesn't see any of them.

**Comment by codeling** [comment] 2021-09-22 13:43
Ah I see - I didn't know the "User Actions Log" yet, interesting, maybe I can use that information directly in a future version...

As to your problem - can you check the bfstop log file if it maybe contains something? The "System - Brute Force Stop" is also definitely enabled on that system? Since the Brute Force Stop component should warn you if it's not, so I guess that's not it...

For the moment I'm out of ideas. Maybe some more info on the system you're running this on could help - what Joomla version is it? What database? Which server software, php version etc.?

**Comment by codeling** [comment] 2022-06-19 12:06
@extreme855 did you have a chance to look into this a bit more? I cannot currently reproduce your issue, and am waiting for more information from your side (see questions in my previous post).

**Comment by codeling** [comment] 2022-10-19 14:53
@extreme855 without feedback there is no way for me to help any further. Closing as non-reproducible, if it still happens, re-open the issue with answers to above questions!

**Closed by codeling** 2022-10-19 14:53 UTC
Labels: question
