### ISSUE TITLE
Notifications are not being sent

### ISSUE THREAD

**Issue by sengels1997** [codeling/bfstop#114] opened 2016-01-13 12:54 UTC
After selecting a user and in another test drive directly entering the email address, no notification is sent whatsoever. Sending a test notification does not work either.

**Comment by codeling** [comment] 2016-01-14 22:36
"Sending a test notification does not work either."
Please elaborate on "does not work". What happens when you try? Do you get an error message? If so, what does it say exactly?

Does emailing work from the rest of your Joomla installation? bfstop just uses the email settings configured in Joomla, have a look there.

Did you check the log file (https://github.com/codeling/bfstop/wiki/FAQ#how-do-i-turn-on-logging), maybe there is something in there.

**Comment by sengels1997** [comment] 2016-01-27 12:40
Sending E-Mails through the backend does work in general. When I try to send a test email from the bfstop plugin, I do not get any error, but it rather says that it was successfully send. I do not receive an email whatsoever.

**Comment by codeling** [comment] 2016-01-27 15:36
Have you checked your Spam filter?
Have you checked the log files?

**Comment by codeling** [comment] 2016-03-15 08:13
Without additional information I cannot reproduce this. Does it still happen?
Did you check your spam filter and log files yet?

**Comment by codeling** [comment] 2016-12-19 08:04
@sengels1997 I am unable to replicate this. Therefore, since I cannot solve this without further information, and my questions above remained unanswered, I will close the issue. If you are still encountering this, feel free to comment here or open a new issue with the requested information.

**Closed by codeling** 2016-12-19 08:04 UTC
Labels: non-reproducible, question
