### ISSUE TITLE
ip unlocking failure

### ISSUE THREAD

**Issue by xiclope** [codeling/bfstop#168] opened 2018-07-03 15:57 UTC
Hello my query is the following one, it does not let me unblock an ip and I can not enter from my ip from my office, thank you very much

**Comment by codeling** [comment] 2018-07-09 11:18
You can find information on how to unblock yourself here: https://github.com/codeling/bfstop/wiki/FAQ#what-can-i-do-in-case-i-have-locked-myself-out
This also works for other IPs.

Though I would be interested why you cannot enter from your IP at your office? Maybe your server is using some complex load balancing or reverse proxy structure that bfstop is not capable of dealing with, and thus it blocks all access?

**Comment by codeling** [comment] 2020-01-05 21:11
@xiclope do you still have this issue? Since you didn't reply back I assume that the issue is either fixed, or that you found a way around it, so I'm closing it. If you should still have that issue please provide more details, as outlined in my comment above!

**Closed by codeling** 2020-01-05 21:11 UTC
Labels: question
