### ISSUE TITLE
Clicking ip address of failed login throws a blant screen

### ISSUE THREAD

**Issue by amundhaugsand** [codeling/bfstop#132] opened 2016-08-23 13:46 UTC
I'm running BF 1.3.0 on Joomla 3.6.2, php 5.6.24. Clicking ip address of failed login or blocked ip renders a blank screen (null response)

**Comment by codeling** [comment] 2016-08-24 08:13
Do you get any error in the bfstop (https://github.com/codeling/bfstop/wiki/FAQ#how-do-i-turn-on-logging), joomla, php or webserver logs?

**Comment by amundhaugsand** [comment] 2016-08-24 13:15
Hi Bernhard,

Nothing in the log files, however with error reporting set to max I get 
a core error message saying

404 - Kan inte hitta View [name, type, prefix]: ipinfo, html, bfstopView

(Kan inte hitta = cannot find)

Could this be of any help?

Best regards,
/Amund

Amund Haugsand

Abilitor utveckling AB
Bergakungsvägen 9
14141 Huddinge

08-5000 8440, 070-878 1687

<http://www.responsive-design.se/>

Abilitor Responsive Design <http://www.responsive-design.se/>
Abilitor utveckling AB <http://www.abilitor.com/>
Den 2016-08-24 kl. 10:13, skrev Bernhard Fröhler:

**Comment by codeling** [comment] 2016-08-25 23:02
Yes this looks helpful; I'll look into it!

**Comment by codeling** [comment] 2016-09-13 06:55
I could reproduce a blank screen, but with a different error message
```
PHP Fatal error:  Cannot declare class idna_convert, because the name is already in use in /srv/http/administrator/components/com_bfstop/helpers/phpwhois/whois.idna.php on line 54, referer: https://mydomain/administrator/index.php?option=com_bfstop
```
It was due to the idna_convert apparently having been introduced in Joomla recently (libraries/idna_convert/).
But I cannot reproduce the error message you show. Could you check whether you have the directory administrator/components/com_bfstop/views/ipinfo , and what it contains?

**Comment by amundhaugsand** [comment] 2016-09-13 16:29
Hi Bernhard,

Yes, I have that directory, it contains files view.html.php and 
index.html, and subdirectory tmpl, which contains index.html and 
default.php . Please let me know if I can help in any way.

Best regards,  /Amund

<http://www.abilitor.com/>
Den 2016-09-13 kl. 08:55, skrev Bernhard Froehler:

**Comment by codeling** [comment] 2016-09-13 19:24
Sounds about right, nothing missing there. I will keep looking, but for the moment I'm out of ideas. Maybe something to do with your language, have you tried setting backend language to english?

**Comment by amundhaugsand** [comment] 2016-09-14 11:28
I changed the backend language to en-GB. The standard Joomla 404 error screen I get when clicking an ip address appears, but still in Swedish.

However, previously I missed the really interesting detail: the uri in the Firefox address field at this point:

http://www.responsive-design.se/administrator/%3Cbr%20/%3E%3Cb%3EDeprecated%3C/b%3E:%20%20Non-static%20method%20BFStopLinkHelper::getIpInfoLink()%20should%20not%20be%20called%20statically,%20assuming%20$this%20from%20incompatible%20context%20in%20%3Cb%3E/home/infocoac/public_html/administrator/components/com_bfstop/views/blocklist/tmpl/default_body.php%3C/b%3E%20on%20line%20%3Cb%3E13%3C/b%3E%3Cbr%20/%3Eindex.php?option=com_bfstop&Itemid=0&view=ipinfo&ipaddress=91.210.147.111

Call stack at this point:

1        JApplicationCms->execute()        /home/infocoac/public_html/index.php:49   
2        JApplicationSite->doExecute()        /home/infocoac/public_html/libraries/cms/application/cms.php:257   
3        JApplicationSite->dispatch()        /home/infocoac/public_html/libraries/cms/application/site.php:230   
4        JComponentHelper::renderComponent()        /home/infocoac/public_html/libraries/cms/application/site.php:191   
5        JComponentHelper::executeComponent()        /home/infocoac/public_html/libraries/cms/component/helper.php:380   
6        require_once()        /home/infocoac/public_html/libraries/cms/component/helper.php:405   
7        JControllerLegacy->execute()        /home/infocoac/public_html/components/com_bfstop/bfstop.php:15   
8        bfstopController->display()        /home/infocoac/public_html/libraries/legacy/controller/legacy.php:702   
9        JControllerLegacy->display()        /home/infocoac/public_html/components/com_bfstop/controller.php:13   
10        JControllerLegacy->getView()        /home/infocoac/public_html/libraries/legacy/controller/legacy.php:619

**Comment by codeling** [comment] 2016-09-14 19:24
Ah that is a good hint!
Seems I fixed that over a year ago: https://github.com/codeling/com_bfstop/commit/5897c866bdf6a7b91bcc023a62e49f24fd600951
But I didn't release it yet unfortunately.
I will try to get a new release (1.4.0) out in the next few weeks (where this fix will be included).
In the meantime you can try to apply the fix yourself (you just need to add the "static" keyword, as in the linked commit).
I will close the issue, please let me know if the issue persists with this fix!

**Closed by codeling** 2016-09-14 19:24 UTC
Labels: bug

**Comment by amundhaugsand** [comment] 2016-09-15 21:24
Yes! Now I too get the message 
`Fatal error: Cannot redeclare class idna_convert in /home/infocoac/public_html/administrator/components/com_bfstop/helpers/phpwhois/whois.idna.php on line 55
`

**Comment by codeling** [comment] 2016-09-15 22:09
The fix for that will also be in the next release.

For now you could apply the changes as shown here:

https://github.com/codeling/com_bfstop/blob/03e5771cb1c0148bb4b5d42454dc2689047bd8e1/admin/helpers/phpwhois/whois.idna.php
