### ISSUE TITLE
rejects emails with more than one dot

### ISSUE THREAD

**Issue by emeyer444** [codeling/bfstop#165] opened 2018-01-25 19:47 UTC
more than one dot in username portion:

my.unworkjin.email@domain.com

Worked great for years, just letting you know.

**Comment by codeling** [comment] 2018-01-25 19:58
You mean in the notification settings? 

When did you first notice this happening? With a specific bfstop version?
But as far as I can tell, I haven't changed anything in the  email address check code. Could have been something that has changed in the Joomla! core (means it would have been introduced with some Joomla! upgrade), as I'm just using the email address data type from there.

**Comment by codeling** [comment] 2018-02-16 21:44
@emeyer444  this works for me without a problem (i can enter such an email address, and I receive the notifications). Please (1) let me know where exactly bfstop "rejects" such an email address (and if there is some error message, and if so what that message says) and (2) tell me a bit more about your server setup. Otherwise I have no clues as to to why you experience this and cannot help you.

**Comment by codeling** [comment] 2018-02-27 08:53
Closing this issue as not reproducible.

**Closed by codeling** 2018-02-27 08:53 UTC
Labels: non-reproducible
