### ISSUE TITLE
Clicking on IP address in Failed Logins returns error

### ISSUE THREAD

**Issue by TheWraith-73** [codeling/bfstop#101] opened 2015-03-18 17:13 UTC
A Joomla error is generated when you click on the IP address of a failed login in the backend.

Error:
500 - View not found [name, type, prefix]: ipinfo, html, bfstopView

The URL is:
http:/<site>/administrator/%3Cbr%20/%3E%3Cb%3EStrict%20Standards%3C/b%3E:%20%20Non-static%20method%20BFStopLinkHelper::getIpInfoLink%28%29%20should%20not%20be%20called%20statically,%20assuming%20$this%20from%20incompatible%20context%20in%20%3Cb%3E/<path>/administrator/components/com_bfstop/views/failedloginlist/tmpl/default_body.php%3C/b%3E%20on%20line%20%3Cb%3E12%3C/b%3E%3Cbr%20/%3Eindex.php?option=com_bfstop&Itemid=0&view=ipinfo&ipaddress=<ip_address>

**Comment by codeling** [comment] 2015-03-18 21:38
The problem encoded in the URL is fixed with https://github.com/codeling/com_bfstop/commit/5897c866bdf6a7b91bcc023a62e49f24fd600951 .

Not sure if that fixes the overall issue here, I couldn't reproduce it yet.

**Comment by codeling** [comment] 2015-06-13 20:46
@TheWraith-73 Would it be posible for you to test whether the commit linked to above fixes the problem?

**Comment by codeling** [comment] 2015-09-15 21:33
Closing, assuming it's fixed.

**Closed by codeling** 2015-09-15 21:33 UTC
Labels: bug, non-reproducible
