### ISSUE TITLE
Error clicking on IP address

### ISSUE THREAD

**Issue by Stevepic** [codeling/bfstop#137] opened 2016-12-23 14:33 UTC
Clicking on an IP address in the list of blocked IPs or failed logins produces the following error:
Fatal error: Cannot redeclare class idna_convert in /home/lincolns/public_html/joomla/administrator/components/com_bfstop/helpers/phpwhois/whois.idna.php on line 55

**Comment by codeling** [comment] 2016-12-27 20:17
Duplicate of https://github.com/codeling/bfstop/issues/132, will be fixed in next release (is already fixed in repositories).

**Closed by codeling** 2016-12-27 20:17 UTC
Labels: bug, duplicate
